ALTER TABLE article ADD page_id INT DEFAULT NULL AFTER id, ADD package_id INT DEFAULT NULL AFTER page_id;
ALTER TABLE article ADD CONSTRAINT FK_23A0E66F44CABFF FOREIGN KEY (package_id) REFERENCES package (id) ON DELETE CASCADE;
ALTER TABLE article ADD CONSTRAINT FK_23A0E66C4663E4 FOREIGN KEY (page_id) REFERENCES page (id) ON DELETE CASCADE;
CREATE INDEX IDX_23A0E66F44CABFF ON article (package_id);
CREATE INDEX IDX_23A0E66C4663E4 ON article (page_id);
